---
abstract: 'Let you use a filehandle in the response body that has ->read but not ->getline'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  HTTP::Request::Common: 0
  IO::File: 0
  Plack::Test: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-AdaptFilehandleRead
requires:
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/jjn1056/Plack-Middleware-AdaptFilehandleRead/issues
  homepage: https://github.com/jjn1056/Plack-Middleware-AdaptFilehandleRead
  repository: https://github.com/jjn1056/Plack-Middleware-AdaptFilehandleRead.git
version: 0.003
